name: Setup Docker Compose
description: Installs latest Docker Compose
runs:
  using: composite
  steps:
    - name: Set up Docker Compose
      uses: docker/setup-compose-action@2fe291b7677a45ee1269ec56a42604c143505e7e # v1.3.0
      with:
        version: latest
